# Generated by Django 4.1.4 on 2023-01-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("username", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=30)),
                ("language", models.IntegerField(choices=[(0, "Unknown"), (1, "Uz"), (2, "Ru")], default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
