# Generated by Django 4.1.4 on 2023-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chat_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
