# Generated by Django 4.1.4 on 2023-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (1, "Student"), (2, "Parent"), (3, "Pupil"), (4, "Job Seeker")], default=0
            ),
        ),
    ]
