# Generated by Django 4.1.4 on 2023-01-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_data",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
