# Generated by Django 4.1.4 on 2023-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webinar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("course", models.IntegerField(choices=[(0, "Unknown"), (1, "Backend"), (2, "Frontend")], default=0)),
                ("name_uz", models.CharField(blank=True, max_length=511, null=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=511, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
