# Generated by Django 4.1.4 on 2023-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinar",
            name="course",
        ),
        migrations.AddField(
            model_name="webinar",
            name="date",
            field=models.DateField(null=True, verbose_name="Release date"),
        ),
    ]
