# Generated by Django 4.1.4 on 2023-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinar", "0003_alter_webinar_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinar",
            name="date",
            field=models.DateTimeField(null=True, verbose_name="Webinar date"),
        ),
    ]
