# Generated by Django 4.1.4 on 2023-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinar", "0005_webinar_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinar",
            name="date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Webinar date"),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="pics"),
        ),
    ]
