# Generated by Django 4.1.4 on 2023-01-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_user_additional_data"),
        ("webinar", "0006_alter_webinar_date_alter_webinar_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
                ("webinar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="webinar.webinar")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
