# Generated by Django 4.1.4 on 2023-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webinar", "0007_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
